# Generated by Django 3.0.5 on 2020-05-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copychecker', '0002_remove_pieceofcopy_creative'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badword', models.CharField(blank=True, max_length=30)),
                ('synonim', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
