# Generated by Django 3.0.5 on 2020-06-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copychecker', '0003_badword'),
    ]

    operations = [
        migrations.AddField(
            model_name='badword',
            name='synonim2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='badword',
            name='synonim3',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
