# Generated by Django 3.0.5 on 2020-06-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copychecker', '0004_auto_20200606_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='badword',
            name='synonim4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='badword',
            name='badword',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='badword',
            name='synonim',
            field=models.CharField(max_length=30),
        ),
    ]
